# Generated by Django 2.1 on 2018-09-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianliang',
            name='time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dianliu',
            name='time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dianya',
            name='time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='gonglv',
            name='time',
            field=models.CharField(max_length=32),
        ),
    ]
