# Generated by Django 2.1 on 2018-10-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0003_user_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gonglv',
        ),
    ]
