# Generated by Django 2.1 on 2018-10-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0004_delete_gonglv'),
    ]

    operations = [
        migrations.CreateModel(
            name='gonglv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('gonglv', models.CharField(max_length=32)),
            ],
        ),
    ]
