# Generated by Django 2.1 on 2018-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0005_gonglv'),
    ]

    operations = [
        migrations.CreateModel(
            name='value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('dianliu', models.CharField(max_length=32)),
                ('dianya', models.CharField(max_length=32)),
                ('dianliang', models.CharField(max_length=32)),
                ('gonglv', models.CharField(max_length=32)),
                ('user_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dianliang',
        ),
        migrations.DeleteModel(
            name='dianliu',
        ),
        migrations.DeleteModel(
            name='dianya',
        ),
        migrations.DeleteModel(
            name='gonglv',
        ),
    ]
