# Generated by Django 2.1 on 2018-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0006_auto_20181003_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
