# Generated by Django 2.1 on 2018-10-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0007_auto_20181003_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SE.user_info'),
        ),
    ]
