# Generated by Django 2.1 on 2018-10-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0008_auto_20181003_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='user_id',
            new_name='user',
        ),
    ]
