# Generated by Django 2.1 on 2018-10-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0009_auto_20181003_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='dianliang',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='dianliu',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='dianya',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='gonglv',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
